GET http://localhost:8080/testFnc/salut

###

POST http://localhost:8080/testFnc
Content-Type: application/json

["salut", "f2"]
###

POST http://localhost:8080/signFunction
Content-Type: application/json

{
  "identifier": "salut",
  "claims": {
    "SmartB": "ent"
  }
}