name: Dev

on: [push]
#on:
#  push:
#    branches: [ main ]

#jobs:
#  Dev:
#    uses: komune-io/fixers-gradle/.github/workflows/dev-workflow.yml@999ef07db02ef8a3d678de4fd326bce73fb7204e
#    permissions:
#      contents: read
#      packages: write
#    secrets:
#      GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
#      GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
#      PKG_MAVEN_USERNAME: ${{ secrets.PKG_MAVEN_USERNAME }}
#      PKG_MAVEN_TOKEN: ${{ secrets.PKG_MAVEN_TOKEN }}

jobs:
  dev:
    uses: komune-io/fixers-gradle/.github/workflows/make-jvm-workflow.yml@29b6c0d48bc37b8ee48f6128cfc6e67d19121932
    permissions:
      contents: read
      packages: write
    secrets:
      GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
      GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
      PKG_MAVEN_USERNAME: ${{ secrets.PKG_MAVEN_USERNAME }}
      PKG_MAVEN_TOKEN: ${{ secrets.PKG_MAVEN_TOKEN }}

  docs:
    uses: komune-io/fixers-gradle/.github/workflows/publish-storybook-workflow.yml@29b6c0d48bc37b8ee48f6128cfc6e67d19121932
    permissions:
      contents: read
      packages: write
      pages: write
      id-token: write
    with:
      with-chromatic: false
      storybook-dir: storybook
      storybook-static-dir: storybook-static
    secrets:
      NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
