name: Docs

on: [push]
#on:
#  push:
#    branches: [ main ]

jobs:
  docs:
    uses: komune-io/fixers-gradle/.github/workflows/publish-storybook-workflow.yml@762586c8818c7886c05a75eb3ef47e9e23e6ea98
    permissions:
      contents: read
      packages: write
      pages: write
      id-token: write
    with:
      with-chromatic: false
      storybook-dir: storybook
      storybook-static-dir: storybook-static
    secrets:
      NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
