name: Docs

on: [push]
#on:
#  push:
#    branches: [ main ]

jobs:
  docs:
    uses: komune-io/fixers-gradle/.github/workflows/publish-storybook-workflow.yml@6e88a784bdb68922b2b42efbda1127a57b79e169
    permissions:
      contents: read
      packages: write
      pages: write
      id-token: write
    with:
      storybook-dir: storybook
      storybook-static-dir: storybook-static
    secrets:
      NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
