name: Docs

on: [push]
#on:
#  push:
#    branches: [ main ]

jobs:
  docs:
    uses: komune-io/fixers-gradle/.github/workflows/publish-storybook-workflow.yml@ff5f228269b8f983edc6d1be998007dcbf9499d2
    permissions:
      contents: read
      packages: write
      pages: write
      id-token: write
    with:
      storybook-dir: storybook
      artifact-name: storybook
      artifact-path: storybook/storybook-static/
    secrets:
      NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
