name: Docs

on: [push]
#on:
#  push:
#    branches: [ main ]

jobs:
  docs:
    uses: komune-io/fixers-gradle/.github/workflows/publish-storybook-workflow.yml@cdfd0b1295e264dd9c4f9669b0cc4dbc838ebdd0
    permissions:
      contents: read
      packages: write
      pages: write
      id-token: write
    with:
      storybook-dir: storybook
      storybook-static-dir: storybook-static
    secrets:
      NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
