name: Sec

on: [push]

jobs:
  Sec:
    uses: komune-io/fixers-gradle/.github/workflows/sec-workflow.yml@7c7698e378589bc31c719f2e6b943ac382216123
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      PKG_GITHUB_USERNAME: ${{ secrets.PKG_GITHUB_USERNAME }}
      PKG_GITHUB_TOKEN: ${{ secrets.PKG_GITHUB_TOKEN }}
    permissions:
      contents: write
      pull-requests: read
      security-events: write
